FROM node:lts-alpine3.21

WORKDIR /usr/src/api

COPY . .

COPY ./.env.production ./.env

RUN npm install --quiet --no-optional --no-fund --loglevel=error

# Gere o cliente Prisma
# RUN npx prisma generate

RUN npm run build

ARG APP_PORT

ENV APP_PORT=${APP_PORT:-3000}

EXPOSE $APP_PORT 

CMD ["npm","run","start:prod"]